### ISSUE TITLE
Pixel Unshuffle is broken

### ISSUE THREAD

**Issue by Kim2091** [victorca25/traiNNer#53]
Training a 1x model with Pixel Unshuffle (using the supplied pretrained model) yields this error:

`[Python] RuntimeError: Given groups=1, weight of size [64, 48, 3, 3], expected input[1, 4, 297, 397] to have 48 channels, but got 4 channels instead
[ESRGAN] Upscaling Error: Index was outside the bounds of the array.
   at Cupscale.PreviewMerger.Merge()
   at Cupscale.Main.Upscale.<Run>d__8.MoveNext()`

**Comment by victorca25** [comment]
This is an error in Cupscale, is it the correct error?

**Comment by kimberly990** [comment]
The error occurred in all forks of ESRGAN when trying to inference with the model. It was specifically about the weights, I didn't mean to copy the Cupscale line
