### ISSUE TITLE
How do i even use this

### ISSUE THREAD

**Issue by Blazeolmo** [victorca25/traiNNer#66]
Why are the installation instructions so complicated? I dont understand this shit.

**Comment by joeyballentine** [comment]
What part about it so you not understand?

**Comment by victorca25** [comment]
What are you trying to do exactly?

If you only plan on using models on your on images/videos, then it's probably better to use simpler projects made for that purpose: https://github.com/victorca25/traiNNer#for-simple-testing.

If it's training your own models, installing is really just making sure you have the [dependencies](https://github.com/victorca25/traiNNer#dependencies) and  cloning this repo (or downloading the zip archive). Alternatively, after downloading this repo you can run:
```
pip install -r requirements.txt optional_requirements.txt
```
to install all the dependencies automatically and you can start using everything, which in most cases using the defaults and following the instructions: https://github.com/victorca25/traiNNer#training will be enough to get you started, this is one of the easiest (if not the easiest) project to get working models with the least effort, but more details about what part you don't understand would be more useful if you need help.
