### ISSUE TITLE
Is there any way to train video super resolution models using this?

### ISSUE THREAD

**Issue by Anirudh-Ve** [victorca25/traiNNer#67]
I can't tell whether its possible to train something like EGVSR or BaicVSR. Is that an upcoming feature?

**Comment by styler00dollar** [comment]
You can train sofvsr and some others with [this config](https://github.com/victorca25/traiNNer/blob/master/codes/options/video/train_video.yml).

**Comment by Anirudh-Ve** [comment]
Thanks a lot! Also is there any more information on EVSRGAN? I can't find anything related to it other than what is mentioned in this repo.

**Comment by styler00dollar** [comment]
[EVSRGAN (Video ESRGAN) and SR3D networks, inspired by the paper 3DSRnet](https://github.com/victorca25/traiNNer/blob/84faf37f511a2b451b9ac7deb8e1f0d6f1b0763f/docs/architectures.md).

**Comment by Anirudh-Ve** [comment]
Alright thanks!
